"use client";
import { useEffect, useState } from "react";
import type { CarProfile } from "../lib/appStorage";
type Props = { car: CarProfile; update: <K extends keyof CarProfile>(key: K, value: CarProfile[K]) => void; dark: boolean; uk: boolean; onSave?: () => void };
export function AdaptiveSettings({ car, update, dark, uk, onSave }: Props) {
  const [mounted, setMounted] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => setMounted(true), []); if (!mounted) return null;
  const rules = car.adaptiveRules ?? []; const currents = [6,8,10,12,14,16,18,20,22,24,26,28,30,32];
  const field = `w-full rounded-xl border px-3 py-2 ${dark ? "border-white/10 bg-white/5 text-white" : "border-black/10 bg-white text-black"}`;
  const setRules = (next: CarProfile["adaptiveRules"]) => update("adaptiveRules", next.map((x) => ({ belowVoltage: Number(x.belowVoltage), current: Number(x.current) })).sort((a,b) => a.belowVoltage - b.belowVoltage));
  const save = () => { onSave?.(); setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  return <section className="mt-8"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xs font-semibold tracking-[.2em] text-cyan-400">ADAPTIVE CHARGING</h2><p className="mt-1 text-sm text-zinc-500">{uk ? "Автоматично підбирає струм за напругою мережі." : "Automatically adjusts current to line voltage."}</p></div><input type="checkbox" checked={car.adaptiveEnabled} onChange={(e) => update("adaptiveEnabled", e.target.checked)} className="h-5 w-5 accent-cyan-400" /></div><div className={`mt-3 grid gap-4 rounded-3xl border p-5 ${dark ? "border-cyan-400/20 bg-cyan-400/[.035]" : "border-cyan-600/20 bg-cyan-500/[.04]"}`}><div className="flex justify-between"><span>{uk ? "Адаптивний режим" : "Adaptive mode"}</span><span className="text-xs text-cyan-400">{car.adaptiveEnabled ? "ON" : "OFF"}</span></div><label><span className="text-xs text-zinc-500">{uk ? "Зупинити зарядку при, В" : "Stop charging at, V"}</span><input type="number" min="150" max="220" value={car.adaptiveStopVoltage} onChange={(e) => update("adaptiveStopVoltage", Number(e.target.value))} className={`mt-1 ${field}`} /></label><div className="flex items-center justify-between"><span className="text-xs tracking-[.15em] text-zinc-500">{uk ? "ПРОМІЖНІ ПРАВИЛА" : "INTERMEDIATE RULES"}</span><button type="button" onClick={() => setRules([...rules, { belowVoltage: 220, current: 14 }])} className="rounded-lg border border-cyan-400/30 px-3 py-1 text-xs text-cyan-400">+ {uk ? "Додати" : "Add"}</button></div>{rules.map((rule,index) => <div key={`${index}-${rule.belowVoltage}`} className="grid grid-cols-[1fr_auto_1fr_auto] items-center gap-2"><input type="number" value={rule.belowVoltage} onChange={(e) => setRules(rules.map((x,i) => i === index ? {...x, belowVoltage: Number(e.target.value)} : x))} className={field}/><span>→</span><select value={rule.current} onChange={(e) => setRules(rules.map((x,i) => i === index ? {...x, current: Number(e.target.value)} : x))} className={field}>{currents.map((value) => <option key={value} value={value}>{value} A</option>)}</select><button type="button" onClick={() => setRules(rules.filter((_,i) => i !== index))} className="text-xl text-red-400">×</button></div>)}<p className="text-xs text-zinc-500">{uk ? "Струми: 6–32 А з кроком 2 А. Критичний поріг зупиняє зарядку." : "Current: 6–32 A in 2 A steps. Critical threshold stops charging."}</p><button type="button" onClick={save} className={`rounded-xl px-4 py-3 font-semibold transition ${saved ? "bg-emerald-400 text-black" : "bg-cyan-400 text-black"}`}>{saved ? (uk ? "✓ Збережено" : "✓ Saved") : (uk ? "Зберегти adaptive налаштування" : "Save adaptive settings")}</button></div></section>;
}
