"use client";
import { useEffect, useState } from "react";
import { BottomNav } from "../../components/BottomNav";
import { getChargers, getActiveChargerId, saveActiveChargerId, saveChargers, getCarProfile, saveCarProfile, type ChargerConfig, type CarProfile } from "../../lib/appStorage";
import { getLanguage, saveLanguage, translations, type Language } from "../../lib/i18n";

export default function SettingsPage() {
  const [chargers, setChargers] = useState<ChargerConfig[]>([]); const [active, setActive] = useState(""); const [id, setId] = useState(""); const [name, setName] = useState(""); const [language, setLanguage] = useState<Language>("en"); const [theme, setTheme] = useState<"dark" | "light">("dark"); const [car, setCar] = useState<CarProfile>(getCarProfile); const [permission, setPermission] = useState<NotificationPermission>("default"); const t = translations[language];
  useEffect(() => { setChargers(getChargers()); setActive(getActiveChargerId() ?? ""); setLanguage(getLanguage()); setTheme((localStorage.getItem("evergy-theme") as "dark" | "light") || "dark"); if (typeof Notification !== "undefined") setPermission(Notification.permission); const sync = () => { setTheme((localStorage.getItem("evergy-theme") as "dark" | "light") || "dark"); setLanguage(getLanguage()); }; window.addEventListener("evergy:theme-change", sync); window.addEventListener("evergy:language-change", sync); return () => { window.removeEventListener("evergy:theme-change", sync); window.removeEventListener("evergy:language-change", sync); }; }, []);
  const dark = theme === "dark"; const updateCar = <K extends keyof CarProfile>(key: K, value: CarProfile[K]) => setCar(current => ({ ...current, [key]: value }));
  const add = () => { const clean = id.trim(); if (!/^[a-z0-9_-]{3,32}$/i.test(clean)) return; const next = [...chargers.filter(c => c.id !== clean), { id: clean, name: name.trim() || clean }]; setChargers(next); saveChargers(next); saveActiveChargerId(clean); setActive(clean); setId(""); setName(""); };
  const remove = (target: string) => { if (!window.confirm("Видалити цю зарядку?")) return; const next = chargers.filter(c => c.id !== target); setChargers(next); saveChargers(next); if (active === target) { const replacement = next[0]?.id ?? ""; setActive(replacement); if (replacement) saveActiveChargerId(replacement); } };
  const input = (key: keyof CarProfile, label: string, type = "text") => <label className="block"><span className="text-xs text-zinc-500">{label}</span><input type={type} value={String(car[key] ?? "")} onChange={e => updateCar(key, type === "number" ? (e.target.value === "" ? null : Number(e.target.value)) as CarProfile[typeof key] : e.target.value as CarProfile[typeof key])} className={`mt-1 w-full rounded-xl border px-4 py-3 ${dark ? "border-white/10 bg-white/5" : "border-black/10 bg-white"}`} /></label>;
  const voltage = car.minimumChargingVoltage ?? 180;
  return <main className={`${dark ? "bg-[#070a0c] text-white" : "bg-[#f4f6f7] text-[#111517]"} min-h-screen`}><div className="mx-auto max-w-[760px] px-5 pb-32 pt-7"><h1 className="text-3xl font-semibold">Налаштування</h1>
    <section className="mt-7 rounded-3xl border border-white/[.07] bg-white/[.02] p-5"><div className="text-xs tracking-[.2em] text-zinc-500">ЗАРЯДКИ</div>{chargers.map(c => <div key={c.id} className="mt-4 flex items-center gap-3 rounded-xl border border-white/10 p-3"><input value={c.name} onChange={e => { const next = chargers.map(x => x.id === c.id ? { ...x, name: e.target.value } : x); setChargers(next); saveChargers(next); }} className="min-w-0 flex-1 bg-transparent outline-none"/><button onClick={() => { setActive(c.id); saveActiveChargerId(c.id); }} className={`rounded-full px-3 py-1 text-xs ${active === c.id ? "bg-cyan-400 text-black" : "bg-white/10 text-zinc-400"}`}>{active === c.id ? "Активна" : "Обрати"}</button><button onClick={() => remove(c.id)} className="text-red-400">×</button></div>)}<div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={id} onChange={e => setId(e.target.value)} placeholder="ID пристрою, наприклад b8351" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3"/><input value={name} onChange={e => setName(e.target.value)} placeholder="Назва зарядки" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3"/></div><button onClick={add} className="mt-3 rounded-xl bg-cyan-400 px-4 py-3 font-semibold text-black">Додати зарядку</button></section>
    <section className="mt-4 grid gap-4 rounded-3xl border border-white/[.07] bg-white/[.02] p-5"><div className="text-xs tracking-[.2em] text-zinc-500">КЕРУВАННЯ ЗАРЯДКОЮ</div><label className="block"><span className="text-sm">Контроль струму витоку</span><select value={car.leakageProtection} onChange={e => { const value = e.target.value as CarProfile["leakageProtection"]; updateCar("leakageProtection", value); updateCar("groundingControl", value !== "off"); }} className={`mt-2 w-full rounded-xl border px-4 py-3 text-base font-semibold ${dark ? "border-white/10 bg-[#10171b]" : "border-black/10 bg-white"}`}><option value="30mA">✓ Увімкнено 30 мА</option><option value="100mA">Увімкнено 100 мА</option><option value="off">Вимкнено</option></select></label><label className="block"><div className="flex items-center justify-between text-sm"><span>Мін. напруга заряджання:</span><span className="font-semibold text-cyan-400">{voltage} В</span></div><input aria-label="Мінімальна напруга заряджання" type="range" min="150" max="210" step="1" value={voltage} onChange={e => updateCar("minimumChargingVoltage", Number(e.target.value))} className="mt-3 w-full accent-blue-500"/><div className="flex justify-between text-sm text-zinc-500"><span>150 В</span><span>210 В</span></div><div className="mx-auto mt-2 w-fit rounded-lg bg-blue-500 px-3 py-1 text-xl font-bold text-white">{voltage} В</div></label><label className="flex items-center justify-between text-sm"><span>Графік заряджання</span><input type="checkbox" checked={car.scheduleEnabled} onChange={e => updateCar("scheduleEnabled", e.target.checked)} /></label><div className="grid grid-cols-2 gap-3">{input("scheduleStart", "Увімкнення", "time")}{input("scheduleEnd", "Вимкнення", "time")}</div><button onClick={() => saveCarProfile(car)} className="rounded-xl bg-cyan-400 px-4 py-3 font-semibold text-black">Зберегти параметри</button></section>
    <section className="mt-4 rounded-3xl border border-white/[.07] bg-white/[.02] p-5"><label className="text-xs tracking-[.2em] text-zinc-500">{t.language}</label><select value={language} onChange={e => { const next = e.target.value as Language; setLanguage(next); saveLanguage(next); }} className={`mt-3 w-full rounded-xl border px-4 py-3 ${dark ? "border-white/10 bg-[#10171b] text-white" : "border-black/10 bg-white text-[#111517]"}`}><option value="uk">Українська</option><option value="en">English</option></select></section>
    <section className="mt-4 rounded-3xl border border-white/[.07] bg-white/[.02] p-5"><div className="text-xs tracking-[.2em] text-zinc-500">СПОВІЩЕННЯ</div><p className="mt-3 text-sm text-zinc-400">{permission === "granted" ? "Сповіщення увімкнені." : "Увімкніть сповіщення, поки застосунок відкритий."}</p><button disabled={permission === "granted" || typeof Notification === "undefined"} onClick={async () => setPermission(await Notification.requestPermission())} className="mt-4 rounded-xl border border-cyan-400/30 px-4 py-3 text-cyan-300 disabled:opacity-40">Увімкнути сповіщення</button></section>
  </div><BottomNav dark={dark} /></main>;
}
